name: Markdown Embed Code From File
author: "@singlecheeze"

description: >
  Synchronize fenced code blocks in Markdown
  with local source files.

inputs:
  markdown:
    description: Markdown file to update
    required: true

runs:
  using: composite
  steps:
    - name: Embed source files
      shell: bash
      env:
        MARKDOWN_FILE: ${{ inputs.markdown }}
      run: |
        python3 "$GITHUB_ACTION_PATH/embed.py" "$MARKDOWN_FILE"

branding:
  icon: bookmark
  color: green